name: Code quality assurance workflow
on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development
jobs:
  publish:
    name: Linting and testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: 4.x
      - run: yarn install
      - run: yarn lint
      - run: yarn test